### ISSUE TITLE
Can I change or reorder the right-click explorer context menu with this extension?

### ISSUE THREAD

**Issue by ghost** [drcika/apc-extension#103]
Here's the doc for the explorer menu (right after editor context menu)
https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups

When I open dev tools, the right-click context menu vanishes, and I can't find any code for `apc.stylesheet`.

**Comment by airtonix** [comment]
One thing we can try is by using subtree modification event breakpoints.

Assuming the context menu is just html in the app.

**Comment by airtonix** [comment]
i think what we're looking for is this: 

```
<div class="context-view" style="top: 0px; left: 0px; z-index: 2575; position: absolute; width: initial;" role="presentation"></div>
```

**Comment by airtonix** [comment]
fixed: 

in your settings: 

```json
  "apc.imports": [
    "${userHome}/.vscode/userscripts.js"
  ],
```

the `~/.vscode/userscripts.js` 

```js

const log = (...args) => console.log('[userscripts] ', ...args)

const createElementSelectionObserver = (selector, callback) => {
    const observer = new MutationObserver((mutations) => {

        let nodes = []
        for (const mutation of mutations) {
            if (mutation.type !== 'childList') {
                continue
            }
            let nodes = mutation.addedNodes
            for (const node of nodes) {
                if (!node.matches(selector)) {
                    continue
                }
                log('found node', node)
                callback(node)
            }

        }

    });

    observer.observe(document.body, {
        childList: true,
        subtree: true,
    })
}

const getNodeInShadowRoot = (selector) => (shadowRoot) => {
    return shadowRoot.querySelector(selector)
}

const createStyleSheet = (css) => {
    const style = document.createElement('style')
    style.type = 'text/css'
    style.appendChild(document.createTextNode(css))
    return style
}

const createStyleSheetAppender = (node) => (css) => {
    log('appending stylesheet to', node)
    const style = createStyleSheet(css)
    node.appendChild(style)
}

log('ready')

function ContextmenuStylesheet () {

    const sheet = new CSSStyleSheet()

    sheet.replaceSync(`
.monaco-menu * {
    font-size: 12px !important;
}
    `)
    return sheet
}

// this one is a shadow root, so we need to adopt the stylesheet
createElementSelectionObserver('.shadow-root-host', (node) => {
    const shadow = node.shadowRoot

    if (!shadow) {
        log('menu has no shadowroot', menu)
        return
    }

    log('shadow: appending stylesheet to', shadow)
    const sheet = ContextmenuStylesheet()
    shadow.adoptedStyleSheets.push(sheet)

})



```

**Comment by airtonix** [comment]
i also use this `~/.vscode/userstyles.css` 

```json
  "apc.imports": [
    "${userHome}/.vscode/userscripts.js",
    "${userHome}/.vscode/userstyles.css"
  ],
```

```css
:root {
    --var-font-size: 12px;
    --var-font-weight: normal;
}

body .monaco-breadcrumbs,
body .monaco-workbench .monaco-action-bar .action-item .action-label,
body .monaco-workbench .monaco-toolbar .action-item .action-label,
body .quick-input-widget,
body .monaco-workbench .part>.content,
body .monaco-workbench .activitybar .menubar.compact>.menubar-menu-button.open .menubar-menu-items-holder.monaco-menu-container *,
body .monaco-workbench .part.titlebar>.titlebar-container>.titlebar-center>.window-title>.command-center .action-item.command-center-center,
.monaco-workbench .part.editor>.content .gettingStartedContainer button,
.monaco-workbench .part.editor>.content .gettingStartedContainer *,
.monaco-pane-view .pane>.pane-header h3.title,
.monaco-workbench *,
#commitTable th, #commitTable td,
.shadow-root-host .monaco-menu-container,
html body .monaco-workbench .monaco-action-bar .action-item .action-label
{
    font-size: var(--var-font-size) !important;
    font-weight: var(--var-font-weight) !important;
}

```

this last one is how you **can** get the context menu when it's created from the sidebar: 

```
html body .monaco-workbench .monaco-action-bar .action-item .action-label
```

i haven't explored more than this.

**Comment by seowner** [comment]
@airtonix sadly this does absolutely nothing to the context menu. It just makes everything else smaller font.

**Comment by lzy1960** [comment]
> this last one is how you **can** get the context menu when it's created from the sidebar:
> 
> ```
> html body .monaco-workbench .monaco-action-bar .action-item .action-label
> ```

Thanks, it works for me! There is no problem with the first-level menu created from the sidebar, but it seems that the submenu cannot use `backdrop-filter`. I wrote it like this:
```css
html body .monaco-workbench .monaco-action-bar .vertical {
    background: #00000000;
    backdrop-filter: blur(8px) !important;
}
```

In addition, `background` can take effect.

Is there any good solution to use `backdrop-filter`?
